kind: Service
apiVersion: v1
metadata:
  name: ollama
spec:
  clusterIP: None
  ipFamilies:
    - IPv4
  ports:
    - name: http
      protocol: TCP
      port: 11434
      targetPort: http
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: ollama
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ollama
spec:
  to:
    kind: Service
    name: ollama
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: nexus.clg.lab:5002/dev-spaces/ollama-code-assist:latest
        imagePullPolicy: Always
        env:
        - name: MODEL_ID
          value: granite-code:8b
        - name: OLLAMA_MODELS
          value: /.ollama/models
        - name: OLLAMA_HOST
          value: 0.0.0.0
        - name: OLLAMA_KEEP_ALIVE
          value: '-1m'
        securityContext:
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
        ports:
        - name: http
          containerPort: 11434
          protocol: TCP
        resources:
          limits:
            cpu: '4'
            memory: 8Gi
          requests:
            cpu: '1'
            memory: 2Gi
        readinessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
          timeoutSeconds: 5
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
          timeoutSeconds: 8
          periodSeconds: 100
          successThreshold: 1
          failureThreshold: 3
        lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh", "-c", "/bin/ollama pull $MODEL_ID" ]
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /.ollama
          name: ollama-cache
      restartPolicy: Always
      volumes:
      - name: ollama-cache
        persistentVolumeClaim:
          claimName: ollama-cache