FROM registry.access.redhat.com/ubi9-minimal

ARG USER_HOME_DIR="/projects/home"
ARG WORK_DIR="/projects"
ARG INSTALL_PACKAGES="procps-ng openssl git tar gzip zip xz unzip which shadow-utils bash zsh vi wget jq podman buildah skopeo podman-docker ca-certificates python3-pip python3-devel fuse-overlayfs util-linux vim-minimal vim-enhanced"
ARG USER_ID=1000

ENV HOME=${USER_HOME_DIR}
ENV BUILDAH_ISOLATION=chroot

COPY --chown=0:0 entrypoint.sh /

RUN microdnf --disableplugin=subscription-manager install -y ${INSTALL_PACKAGES}; \
  microdnf update -y ; \
  microdnf clean all ; \
  mkdir -p /usr/local/bin ; \
  mkdir -p ${WORK_DIR} ; \
  pip3 install -U podman-compose ; \
  pip3 install -U cekit ; \
  chmod +x /entrypoint.sh ; \
  # Create User
  groupadd -g ${USER_ID} users
  useradd -u ${USER_ID} -g users -d ${HOME} user
  # Setup for rootless podman
  setcap cap_setuid+ep /usr/bin/newuidmap ; \
  setcap cap_setgid+ep /usr/bin/newgidmap ; \
  START_ID=$(( ${USER_ID}+1 )) ; \
  END_ID=$(( 65536-${START_ID} )) ; \
  echo "${USER}:${START_ID}:${END_ID}" > /etc/subuid ; \
  echo "${USER}:${START_ID}:${END_ID}" > /etc/subgid ; \
  # Create Sym Links for OpenShift CLI (Assumed to be retrieved by an init-container)
  ln -s /projects/bin/oc /usr/local/bin/oc ; \
  ln -s /projects/bin/kubectl /usr/local/bin/kubectl

USER 1000
WORKDIR ${WORK_DIR}
ENTRYPOINT ["/usr/libexec/podman/catatonit","--","/entrypoint.sh"]
CMD [ "tail", "-f", "/dev/null" ]