FROM registry.access.redhat.com/ubi9

ARG INSTALL_PACKAGES="procps-ng openssl libbrotli git tar gzip zip xz unzip which shadow-utils bash zsh vi wget jq podman buildah skopeo podman-docker ca-certificates python python-pip python-devel fuse-overlayfs util-linux vim-minimal vim-enhanced zlib-devel libffi-devel libstdc++-devel glibc-langpack-en autoconf automake binutils bison flex gcc gcc-c++ gdb glibc-devel libtool make pkgconf pkgconf-m4 pkgconf-pkg-config strace cmake webkit2gtk3-devel openssl-devel curl libappindicator-gtk3 librsvg2-devel mise"

WORKDIR /
USER 0

RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm ; \
  dnf install -y dnf-plugins-core ; \
  dnf config-manager --add-repo https://mise.jdx.dev/rpm/mise.repo ; \
  dnf install -y --allowerasing ${INSTALL_PACKAGES} ; \
  dnf update -y ; \
  dnf clean all ; \
  git clone https://github.com/aws/amazon-q-developer-cli ; \
  cd amazon-q-developer-cli ; \
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > /rustup-init.sh ; \
  chmod 755 /rustup-init.sh ; \
  /rustup-init.sh -y ; \
  . /root/.cargo/env ; \
  rustup default stable ; \
  eval "$(mise activate bash)" ; \
  mise trust ; \
  mise install ; \
  cargo build -p q_cli

