FROM registry.access.redhat.com/ubi9:9.6

ARG USER_HOME_DIR="/home/user"
ARG WORK_DIR="/projects"
ARG INSTALL_PACKAGES="procps-ng openssl libbrotli git tar gzip zip xz unzip which shadow-utils bash zsh vi wget jq podman buildah skopeo podman-docker ca-certificates python python-pip python-devel fuse-overlayfs util-linux vim-minimal vim-enhanced helm kustomize"

ENV HOME=${USER_HOME_DIR}
ENV BUILDAH_ISOLATION=chroot

COPY --chown=0:0 entrypoint.sh /

RUN set -e ; \
  dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm ; \
  dnf install -y ${INSTALL_PACKAGES} ; \
  dnf update -y ; \
  dnf clean all ; \
  mkdir -p /usr/local/bin ; \
  mkdir -p ${WORK_DIR} ; \
  pip install -U podman-compose ; \
  pip install -U cekit ; \
  chmod +x /entrypoint.sh ; \
  #
  # Setup for root-less podman
  #
  mkdir -p ${USER_HOME_DIR} ; \
  chown -R 1000:1000 ${USER_HOME_DIR} ; \
  echo "user:x:1000:1000:devspaces user:${USER_HOME_DIR}:/bin/bash" >> /etc/passwd ; \
  echo "user:x:1000:" >> /etc/group ; \
  echo "user:1001:64535" >> /etc/subuid ; \
  echo "user:1001:64535" >> /etc/subgid ; \
  setcap cap_setuid+ep /usr/bin/newuidmap ; \
  setcap cap_setgid+ep /usr/bin/newgidmap ; \
  #
  # Create Sym Links for OpenShift CLI (Assumed to be retrieved by an init-container)
  #
  ln -s /projects/bin/oc /usr/local/bin/oc ; \
  ln -s /projects/bin/kubectl /usr/local/bin/kubectl

USER 1000
WORKDIR ${WORK_DIR}
ENTRYPOINT ["/usr/libexec/podman/catatonit","--","/entrypoint.sh"]
CMD [ "tail", "-f", "/dev/null" ]